pep8_test_models:
	pycodestyle tests/test_models/*.py

pep8_models:
	pycodestyle models/*.py

test_base:
	python3 -m unittest tests/test_models/test_base.py

test_rectangle:
	python3 -m unittest tests/test_models/test_rectangle.py

test_square:
	python3 -m unittest tests/test_models/test_square.py